#Thu Aug 20 14:45:36 CEST 2026
BUILD_TYPE_MINIFIED_DEBUG=minifiedDebug
DATA_PROTECTION_LAST_UPDATED=2022-01-06
DEBUG_TEST_IDS_ENABLED=true
PUSH_NOTIFICATION_DEBUG_INITIAL_SHARED_SECRET=f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2
PUSH_NOTIFICATION_DEBUG_KEY_IDENTIFIER=test-key-id-replace-with-real-uuid
PUSH_NOTIFICATION_DEBUG_TIME_ISS_CREATED=2023-10
TEST_INSTRUMENTATION_ORCHESTRATOR=androidx.test.runner.AndroidJUnitRunner
USER_AGENT=eRp-App-Android/1.39.2 GMTIK
VAU_OCSP_RESPONSE_MAX_AGE=12
VERSION_CODE=4028
VERSION_NAME=1.39.2-RC1
android.analyticsEnabled=false
android.defaults.buildfeatures.buildconfig=true
android.enableJetifier=false
android.experimental.r8.dex.vmoptions=-Xmx11g
android.experimental.testOptions.managedDevices.maxConcurrentDevices=1
android.experimental.testOptions.managedDevices.setupTimeoutMinutes=180
android.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
android.useAndroidX=true
buildkonfig.flavor=googleTuInternal
kotlin.code.style=official
kotlin.daemon.jvm.options="-Xmx11g"
kotlin.jvm.target.validation.mode=IGNORE
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.mpp.stability.nowarn=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.java.installations.auto-download=true
org.gradle.jvmargs=-Xmx11g -XX\:+UseG1GC
org.gradle.parallel=true
org.gradle.workers.max=6
org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
systemProp.gradle.disallowInsecureProtocol=true
