/*
 * Copyright (Change Date see Readme), gematik GmbH
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the
 * European Commission – subsequent versions of the EUPL (the "Licence").
 * You may not use this work except in compliance with the Licence.
 *
 * You find a copy of the Licence in the "Licence" file or at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
 * In case of changes by gematik GmbH find details in the "Readme" file.
 *
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik find details in the "Readme" file.
 */

@file:Suppress("ktlint:max-line-length", "MayBeConst")

package de.gematik.ti.erp.app.vau

import de.gematik.ti.erp.app.vau.api.model.UntrustedCertList
import de.gematik.ti.erp.app.vau.api.model.UntrustedOCSPList
import kotlinx.datetime.Instant
import kotlinx.serialization.json.Json
import okio.ByteString.Companion.decodeBase64
import org.bouncycastle.cert.X509CertificateHolder
import org.bouncycastle.jce.provider.BouncyCastleProvider
import java.security.SecureRandom

val BCProvider = BouncyCastleProvider()

val TestCryptoConfig = object : VauCryptoConfig {
    override val provider = BCProvider
    override val random = SecureRandom()
}

fun x509PEMCertificateAsBase64(data: String) =
    data.removePrefix("-----BEGIN CERTIFICATE-----")
        .removeSuffix("-----END CERTIFICATE-----").replace("\n", "").trim()

fun x509Certificate(data: String) =
    X509CertificateHolder(x509PEMCertificateAsBase64(data).decodeBase64()!!.toByteArray())

fun base64X509Certificate(certInBase64: String) =
    X509CertificateHolder(certInBase64.decodeBase64()!!.toByteArray())

object TestCertificates {

    object Vau {
        val OID = byteArrayOf(6, 8, 42, -126, 20, 0, 76, 4, -126, 2) // oid = 1.2.276.0.76.4.258

        const val Base64 =
            "MIIC7jCCApWgAwIBAgIHATwrYu8gtzAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMDEwMDcwMDAwMDBaFw0yNTA4MDcwMDAwMDBaMF4xCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1QtT05MWSAtIE5PVC1WQUxJRDEnMCUGA1UEAwweRVJQIFJlZmVyZW56ZW50d2lja2x1bmcgRkQgRW5jMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABKYLzjl704qFX+oEuUOyLV70i2Bn2K4jekh/YOxExtdADB3X/q7fX/tVr09GtDRxe3h1yov9TwuHaHYh91RlyMejggEUMIIBEDAMBgNVHRMBAf8EAjAAMCEGA1UdIAQaMBgwCgYIKoIUAEwEgSMwCgYIKoIUAEwEgUowHQYDVR0OBBYEFK5+wVL9g8tGve6b1MdHK1xs62H7MDgGCCsGAQUFBwEBBCwwKjAoBggrBgEFBQcwAYYcaHR0cDovL2VoY2EuZ2VtYXRpay5kZS9vY3NwLzAOBgNVHQ8BAf8EBAMCAwgwUwYFKyQIAwMESjBIMEYwRDBCMEAwMgwwRS1SZXplcHQgdmVydHJhdWVuc3fDvHJkaWdlIEF1c2bDvGhydW5nc3VtZ2VidW5nMAoGCCqCFABMBIICMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMAoGCCqGSM49BAMCA0cAMEQCIGZ20lLY2WEAGOTmNEFBB1EeU645fE0Iy2U9ypFHMlw4AiAVEP0HYut0Z8sKUk6WVanMmKXjfxO/qgQFzjsbq954dw=="
        val X509Certificate by lazy { base64X509Certificate(Base64) }

        const val SerialNumber = "347632017809591"

        // TODO second ca is ocsp response only; production ocsp uses same ca as vau/idp
        val JsonCertList = """
            {
                "add_roots": [
                "MIIDYDCCAkigAwIBAgIUUnQ6d1ZcA0I1VNMeG42Q+iLxcDYwDQYJKoZIhvcNAQELBQAwQTEbMBkGA1UEAwwSR0VNLlJDQTMgVEVTVC1PTkxZMRUwEwYDVQQKDAxnZW1hdGlrIEdtYkgxCzAJBgNVBAYTAkRFMB4XDTI1MDcyOTEzNTkyMloXDTMwMDcyODEzNTkyMlowQTEbMBkGA1UEAwwSR0VNLlJDQTQgVEVTVC1PTkxZMRUwEwYDVQQKDAxnZW1hdGlrIEdtYkgxCzAJBgNVBAYTAkRFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwEOxCaI5UGNWhPQBWAdfC9g12OugRiA6NL5rWVQefHwPQicpRZkHdqHvHk/aW3LWpIW1kuVgPF+AQTwLG5swIL6qGut0AVvktSwHqb2TnsqM1diWiV2nkb31cmy2D6QGxI8iBfI9Z9/C03zUvpA7ko/2pam/GSXdWPU3cekEGhX4b9aBK6cgFQrQLU1e/tD71thLZhonLKrTaqubfAZUXV4QkilgAA6vNPZ71mrbTx3GYaUaiza2eq1YqK/MVX/dTSTshnkMRbpxtgEYwsigcVrS5dl9DoUlbVglTvE9VIMjRcp1nUrOtVcnSgMZ5XD1zTi0/uN9shjOcLD1C+3OAwIDAQABo1AwTjAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBTxpcwJdB1Is9vn6YLXysYJoaMn4DAfBgNVHSMEGDAWgBSXGD1yTYoo0Y6jJI505UoVrVUm+jANBgkqhkiG9w0BAQsFAAOCAQEAgmN7VBqN5Fr1c38qSnG5D4uf3p1rsXhoRVu/7DSRvpDbAoxuZbncomuNFnBAcnrg58/7q9Mc8W6KzwL1iAmaYRoIMP5GnfhhFasu+cw/0LL1o0aFyUhABErM4hTIN/kCLZP71W8noT343MpmbX4nejLx0fODwjxCIgnyIhboM/yFuFDPWaIUP2Zk2CvidH2hGlnZdg5yr3wL7eV+OS1EzA2CN06s9odl0jQC62kKNKY4JKY99DVCSycRLOMNDDXlHdnp0M1aB06zTO59cjLK3oHSv3gd9gRrG3UeLM+rGJV+31GhAZQzijjMzRcl5/yUo5gRS8Oy905bvGLnRewtJQ==",
                "MIIDYDCCAkigAwIBAgIUKKYpbTkuqntAXNJMuJIIaPfn6ywwDQYJKoZIhvcNAQELBQAwQTEbMBkGA1UEAwwSR0VNLlJDQTQgVEVTVC1PTkxZMRUwEwYDVQQKDAxnZW1hdGlrIEdtYkgxCzAJBgNVBAYTAkRFMB4XDTI1MDczMDA3NDczOVoXDTMwMDcyOTA3NDczOVowQTEbMBkGA1UEAwwSR0VNLlJDQTUgVEVTVC1PTkxZMRUwEwYDVQQKDAxnZW1hdGlrIEdtYkgxCzAJBgNVBAYTAkRFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoUwQ6dVqECn7ZRbKrHLW8eGUuRDzVSIhVx3Jy9PVQ+NicTBsYdz3Dr7myBOTj1SnmdaSVjEvD53gd7fbsijfoRoD7JJcCgUd/osESDsi3Onc0l0/KiZ73nCTB3wLUcA7SaizBcKVteOBOH++TUZdhQYpKieh6rETpCI8SZoX3STlC23kykVyP2Bfc5vr2oHFBsM6uMuu+Dt3eQu/R9iwQxkNPeKag7nAVO0Em0kYJ90oLh+GMcTad2qRmlgCNx/jkm4MAsWhzDDr/dJYRW/3Xq9fSLCdUxXw9X8cVqWvA7LyDqj0M9NlNNRlgr5BCrjzXpGlz/QOBzDqQkx+ODBJZwIDAQABo1AwTjAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBS2/1BruqFKh8SEkXMP4t/Opkvi4zAfBgNVHSMEGDAWgBTxpcwJdB1Is9vn6YLXysYJoaMn4DANBgkqhkiG9w0BAQsFAAOCAQEAG07RkU12HXcTuPMKPv05PcwngYGtkZKSorVF4Sc5V1K0QMfhf3MrES5g4MuHtxCxeFtLvmt0+cyP7KiuRbsVIXv9uUriUEMEh8vvdDsmaR9iIQuuT9NGMNqUbF8PndLSeIKPUCtGFy0vKFg2dJa6I0E2My7H89v4AptRgE99g5v4+uxsJH13l2bitmnihS0uvrClOflFS45+KwbMtYzTnXwCPg9J0MmmLbd0pRNeGchabIGiij/b2nPgeUX1XUDVfPebZkH0E5f/wZMxT0l3DovNpuimSkePeG9Z91uxigAUFkq4rDKNbPddMLGmZXvRE3CNWqtOh/boqy6U4O39RQ==",
                "MIIDYDCCAkigAwIBAgIUeFb1OY8qni7S6PAvwim7x3ZUEPEwDQYJKoZIhvcNAQELBQAwQTEbMBkGA1UEAwwSR0VNLlJDQTUgVEVTVC1PTkxZMRUwEwYDVQQKDAxnZW1hdGlrIEdtYkgxCzAJBgNVBAYTAkRFMB4XDTI1MDczMDA4MDY0NloXDTMwMDcyOTA4MDY0NlowQTEbMBkGA1UEAwwSR0VNLlJDQTUgVEVTVC1PTkxZMRUwEwYDVQQKDAxnZW1hdGlrIEdtYkgxCzAJBgNVBAYTAkRFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlBzBjs/NDUHw3wLb1U6tZmO6eVcRFRHziX7fmDLZFqVMOsBelKmgLXQNZJrjxmjCh52xq60UyjlUkR7zPV69LVClkheclZ/5Xsfvsr9MEQjcoKKFjOW14aIsw8eY5NGdugULf0YGnueyLr42+XHBiIrNZ0OFy31NYQD85utCYy+/RJsmL6A9u+ra+i5cX53Zb0RWhz5lzqHg5RfTEShAObyupt1fK6xW00noOs6jG7Mi6lh7NFQMSY7Qgt4HMuO6YCWEdy9Vl2cyyHoL7068K+lQpzAcJkPZmeOZdLTy+MHV/eg13lZ08qCthQZ7eFyRlxojtbKifPvNHNfWZwrj8QIDAQABo1AwTjAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBT0fcMPbydwR5OXocf1CnfoweuXxzAfBgNVHSMEGDAWgBS2/1BruqFKh8SEkXMP4t/Opkvi4zANBgkqhkiG9w0BAQsFAAOCAQEAdH54bEuqu03iB3wsaVukvJ7HYusKPoEJCjpTlZ50G62TOZ3LAiGdF7RxxaYEygnVOiKsK1ZgrAhhRTsSJptEsAxnTvXvX+C+rm99ays6ExZoyj1aTDBM9E7pvEvd03VB6KZeZ73L2PR35xodfL5NBqRmLS8YRcpJiKl0vLyAhuTPIEZe56NwJ/OJZSLftUA9OwNUKTjOuGViD/dg8GxdnkUZTeOaGgXM2Uz0PbKNhlZ8F3zMlIlYrA25/Z0Wu27rIXXChf4lEMRBAGrQqe4Qc5GI5B1WOqdEWBxXnEdGHB7CUZ6ZgAaRoWcNG3V5JEPXOA7rGSNT7O7yg25dkOni0g=="
                 ],
                "ca_certs": [
                    "MIIDGjCCAr+gAwIBAgIBFzAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxlIFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdFTS5SQ0EzIFRFU1QtT05MWTAeFw0xNzA4MzAxMTM2MjJaFw0yNTA4MjgxMTM2MjFaMIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABDFinQgzfsT1CN0QWwdm7e2JiaDYHocCiy1TWpOPyHwoPC54RULeUIBJeX199Qm1FFpgeIRP1E8cjbHGNsRbju6jggEgMIIBHDAdBgNVHQ4EFgQUKPD45qnId8xDRduartc6g6wOD6gwHwYDVR0jBBgwFoAUB5AzLXVTXn/4yDe/fskmV2jfONIwQgYIKwYBBQUHAQEENjA0MDIGCCsGAQUFBzABhiZodHRwOi8vb2NzcC5yb290LWNhLnRpLWRpZW5zdGUuZGUvb2NzcDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMFsGA1UdEQRUMFKgUAYDVQQKoEkMR2dlbWF0aWsgR2VzZWxsc2NoYWZ0IGbDvHIgVGVsZW1hdGlrYW53ZW5kdW5nZW4gZGVyIEdlc3VuZGhlaXRza2FydGUgbWJIMAoGCCqGSM49BAMCA0kAMEYCIQCprLtIIRx1Y4mKHlNngOVAf6D7rkYSa723oRyX7J2qwgIhAKPi9GSJyYp4gMTFeZkqvj8pcAqxNR9UKV7UYBlHrdxC"
                ],
                "ee_certs": [
                    "MIIC7jCCApWgAwIBAgIHATwrYu8gtzAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMDEwMDcwMDAwMDBaFw0yNTA4MDcwMDAwMDBaMF4xCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1QtT05MWSAtIE5PVC1WQUxJRDEnMCUGA1UEAwweRVJQIFJlZmVyZW56ZW50d2lja2x1bmcgRkQgRW5jMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABKYLzjl704qFX+oEuUOyLV70i2Bn2K4jekh/YOxExtdADB3X/q7fX/tVr09GtDRxe3h1yov9TwuHaHYh91RlyMejggEUMIIBEDAMBgNVHRMBAf8EAjAAMCEGA1UdIAQaMBgwCgYIKoIUAEwEgSMwCgYIKoIUAEwEgUowHQYDVR0OBBYEFK5+wVL9g8tGve6b1MdHK1xs62H7MDgGCCsGAQUFBwEBBCwwKjAoBggrBgEFBQcwAYYcaHR0cDovL2VoY2EuZ2VtYXRpay5kZS9vY3NwLzAOBgNVHQ8BAf8EBAMCAwgwUwYFKyQIAwMESjBIMEYwRDBCMEAwMgwwRS1SZXplcHQgdmVydHJhdWVuc3fDvHJkaWdlIEF1c2bDvGhydW5nc3VtZ2VidW5nMAoGCCqCFABMBIICMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMAoGCCqGSM49BAMCA0cAMEQCIGZ20lLY2WEAGOTmNEFBB1EeU645fE0Iy2U9ypFHMlw4AiAVEP0HYut0Z8sKUk6WVanMmKXjfxO/qgQFzjsbq954dw==",
                    "MIICsTCCAligAwIBAgIHA61I5ACUjTAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMDA4MDQwMDAwMDBaFw0yNTA4MDQyMzU5NTlaMEkxCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1QtT05MWSAtIE5PVC1WQUxJRDESMBAGA1UEAwwJSURQIFNpZyAxMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABJZQrG1NWxIB3kz/6Z2zojlkJqN3vJXZ3EZnJ6JXTXw5ZDFZ5XjwWmtgfomv3VOV7qzI5ycUSJysMWDEu3mqRcajge0wgeowHQYDVR0OBBYEFJ8DVLAZWT+BlojTD4MT/Na+ES8YMDgGCCsGAQUFBwEBBCwwKjAoBggrBgEFBQcwAYYcaHR0cDovL2VoY2EuZ2VtYXRpay5kZS9vY3NwLzAMBgNVHRMBAf8EAjAAMCEGA1UdIAQaMBgwCgYIKoIUAEwEgUswCgYIKoIUAEwEgSMwHwYDVR0jBBgwFoAUKPD45qnId8xDRduartc6g6wOD6gwLQYFKyQIAwMEJDAiMCAwHjAcMBowDAwKSURQLURpZW5zdDAKBggqghQATASCBDAOBgNVHQ8BAf8EBAMCB4AwCgYIKoZIzj0EAwIDRwAwRAIgVBPhAwyX8HAVH0O0b3+VazpBAWkQNjkEVRkv+EYX1e8CIFdn4O+nivM+XVi9xiKK4dW1R7MD334OpOPTFjeEhIVV",
                    "MIICsTCCAligAwIBAgIHAbssqQhqOzAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMTAxMTUwMDAwMDBaFw0yNjAxMTUyMzU5NTlaMEkxCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1QtT05MWSAtIE5PVC1WQUxJRDESMBAGA1UEAwwJSURQIFNpZyAzMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABIYZnwiGAn5QYOx43Z8MwaZLD3r/bz6BTcQO5pbeum6qQzYD5dDCcriw/VNPPZCQzXQPg4StWyy5OOq9TogBEmOjge0wgeowDgYDVR0PAQH/BAQDAgeAMC0GBSskCAMDBCQwIjAgMB4wHDAaMAwMCklEUC1EaWVuc3QwCgYIKoIUAEwEggQwIQYDVR0gBBowGDAKBggqghQATASBSzAKBggqghQATASBIzAfBgNVHSMEGDAWgBQo8Pjmqch3zENF25qu1zqDrA4PqDA4BggrBgEFBQcBAQQsMCowKAYIKwYBBQUHMAGGHGh0dHA6Ly9laGNhLmdlbWF0aWsuZGUvb2NzcC8wHQYDVR0OBBYEFC94M9LgW44lNgoAbkPaomnLjS8/MAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDRwAwRAIgCg4yZDWmyBirgxzawz/S8DJnRFKtYU/YGNlRc7+kBHcCIBuzba3GspqSmoP1VwMeNNKNaLsgV8vMbDJb30aqaiX1"
                ]
            }
        """.trimIndent()

        val CertList: UntrustedCertList by lazy { Json.decodeFromString(JsonCertList) }

        val ValidTimestamp: Instant = Instant.fromEpochSeconds(1615368104) // 2021-03-10T09:21:44.000Z
        val ExpiredTimestamp: Instant =
            Instant.fromEpochSeconds(1899364896) // 2030-03-10T09:21:36.812Z
    }

    object Idp1 {
        val OID = byteArrayOf(6, 8, 42, -126, 20, 0, 76, 4, -126, 4) // oid = 1.2.276.0.76.4.260

        const val Base64 =
            "MIICsTCCAligAwIBAgIHA61I5ACUjTAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMDA4MDQwMDAwMDBaFw0yNTA4MDQyMzU5NTlaMEkxCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1QtT05MWSAtIE5PVC1WQUxJRDESMBAGA1UEAwwJSURQIFNpZyAxMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABJZQrG1NWxIB3kz/6Z2zojlkJqN3vJXZ3EZnJ6JXTXw5ZDFZ5XjwWmtgfomv3VOV7qzI5ycUSJysMWDEu3mqRcajge0wgeowHQYDVR0OBBYEFJ8DVLAZWT+BlojTD4MT/Na+ES8YMDgGCCsGAQUFBwEBBCwwKjAoBggrBgEFBQcwAYYcaHR0cDovL2VoY2EuZ2VtYXRpay5kZS9vY3NwLzAMBgNVHRMBAf8EAjAAMCEGA1UdIAQaMBgwCgYIKoIUAEwEgUswCgYIKoIUAEwEgSMwHwYDVR0jBBgwFoAUKPD45qnId8xDRduartc6g6wOD6gwLQYFKyQIAwMEJDAiMCAwHjAcMBowDAwKSURQLURpZW5zdDAKBggqghQATASCBDAOBgNVHQ8BAf8EBAMCB4AwCgYIKoZIzj0EAwIDRwAwRAIgVBPhAwyX8HAVH0O0b3+VazpBAWkQNjkEVRkv+EYX1e8CIFdn4O+nivM+XVi9xiKK4dW1R7MD334OpOPTFjeEhIVV"
        val X509Certificate by lazy { base64X509Certificate(Base64) }

        const val SerialNumber = "1034953504625805"
    }

    object Idp2 {
        val OID = byteArrayOf(6, 8, 42, -126, 20, 0, 76, 4, -126, 4) // oid = 1.2.276.0.76.4.260

        const val Base64 =
            "MIICsTCCAligAwIBAgIHAbssqQhqOzAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMTAxMTUwMDAwMDBaFw0yNjAxMTUyMzU5NTlaMEkxCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1QtT05MWSAtIE5PVC1WQUxJRDESMBAGA1UEAwwJSURQIFNpZyAzMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABIYZnwiGAn5QYOx43Z8MwaZLD3r/bz6BTcQO5pbeum6qQzYD5dDCcriw/VNPPZCQzXQPg4StWyy5OOq9TogBEmOjge0wgeowDgYDVR0PAQH/BAQDAgeAMC0GBSskCAMDBCQwIjAgMB4wHDAaMAwMCklEUC1EaWVuc3QwCgYIKoIUAEwEggQwIQYDVR0gBBowGDAKBggqghQATASBSzAKBggqghQATASBIzAfBgNVHSMEGDAWgBQo8Pjmqch3zENF25qu1zqDrA4PqDA4BggrBgEFBQcBAQQsMCowKAYIKwYBBQUHMAGGHGh0dHA6Ly9laGNhLmdlbWF0aWsuZGUvb2NzcC8wHQYDVR0OBBYEFC94M9LgW44lNgoAbkPaomnLjS8/MAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDRwAwRAIgCg4yZDWmyBirgxzawz/S8DJnRFKtYU/YGNlRc7+kBHcCIBuzba3GspqSmoP1VwMeNNKNaLsgV8vMbDJb30aqaiX1"
        val X509Certificate by lazy { base64X509Certificate(Base64) }

        const val SerialNumber = "487275465566779"
    }

    object Idp3 {
        val OID = byteArrayOf(6, 8, 42, -126, 20, 0, 76, 4, -126, 4) // oid = 1.2.276.0.76.4.260

        private val data = """
            -----BEGIN CERTIFICATE-----
            MIICsTCCAligAwIBAgIHA8OQFtdAtTAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMC
            REUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtv
            bXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQD
            DBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMTAxMTMwMDAwMDBaFw0yNjAx
            MTMyMzU5NTlaMEkxCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1Qt
            T05MWSAtIE5PVC1WQUxJRDESMBAGA1UEAwwJSURQIFNpZyAyMFowFAYHKoZIzj0C
            AQYJKyQDAwIIAQEHA0IABEC6Sfy6RcfusiYbG+Drx8FNZIS574ojsGDr5n+XJSu8
            mHuknfNkoMmSbytt4br0YGihOixcmBKy80UfSLdXGe6jge0wgeowDgYDVR0PAQH/
            BAQDAgeAMC0GBSskCAMDBCQwIjAgMB4wHDAaMAwMCklEUC1EaWVuc3QwCgYIKoIU
            AEwEggQwIQYDVR0gBBowGDAKBggqghQATASBSzAKBggqghQATASBIzAfBgNVHSME
            GDAWgBQo8Pjmqch3zENF25qu1zqDrA4PqDA4BggrBgEFBQcBAQQsMCowKAYIKwYB
            BQUHMAGGHGh0dHA6Ly9laGNhLmdlbWF0aWsuZGUvb2NzcC8wHQYDVR0OBBYEFLM7
            Gd6tlX+bjswtS+tVxkbTwxC0MAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDRwAw
            RAIgfKKll8KtEPLdaUWwF7ftbEvkIdz9KXhL4cKRyozGQjECIDxby8TX2iWfwVhf
            HoxmpTf+D3eCRHhmnwJWcIgm1tF0
            -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }

        const val SerialNumber = "1059448556044469"
    }

    object Idp4 {
        val OID = byteArrayOf(6, 8, 42, -126, 20, 0, 76, 4, -126, 4) // oid = 1.2.276.0.76.4.260

        private val data = """
            -----BEGIN CERTIFICATE-----
            MIICsTCCAligAwIBAgIHAbssqQhqOzAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMC
            REUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtv
            bXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQD
            DBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMTAxMTUwMDAwMDBaFw0yNjAx
            MTUyMzU5NTlaMEkxCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1Qt
            T05MWSAtIE5PVC1WQUxJRDESMBAGA1UEAwwJSURQIFNpZyAzMFowFAYHKoZIzj0C
            AQYJKyQDAwIIAQEHA0IABIYZnwiGAn5QYOx43Z8MwaZLD3r/bz6BTcQO5pbeum6q
            QzYD5dDCcriw/VNPPZCQzXQPg4StWyy5OOq9TogBEmOjge0wgeowDgYDVR0PAQH/
            BAQDAgeAMC0GBSskCAMDBCQwIjAgMB4wHDAaMAwMCklEUC1EaWVuc3QwCgYIKoIU
            AEwEggQwIQYDVR0gBBowGDAKBggqghQATASBSzAKBggqghQATASBIzAfBgNVHSME
            GDAWgBQo8Pjmqch3zENF25qu1zqDrA4PqDA4BggrBgEFBQcBAQQsMCowKAYIKwYB
            BQUHMAGGHGh0dHA6Ly9laGNhLmdlbWF0aWsuZGUvb2NzcC8wHQYDVR0OBBYEFC94
            M9LgW44lNgoAbkPaomnLjS8/MAwGA1UdEwEB/wQCMAAwCgYIKoZIzj0EAwIDRwAw
            RAIgCg4yZDWmyBirgxzawz/S8DJnRFKtYU/YGNlRc7+kBHcCIBuzba3GspqSmoP1
            VwMeNNKNaLsgV8vMbDJb30aqaiX1
            -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    /**
     * First response of [OCSP].
     */
    object OCSP1 {
        const val Base64 =
            "MIIEFgoBAKCCBA8wggQLBgkrBgEFBQcwAQEEggP8MIID+DCB+6FZMFcxCzAJBgNVBAYTAkRFMRowGAYDVQQKDBFnZW1hdGlrIE5PVC1WQUxJRDEsMCoGA1UEAwwjT0NTUCBTaWduZXIgS29tcC1DQTEwIGVjYyBURVNULU9OTFkYDzIwMjEwNTE3MDYyMzAxWjBoMGYwPjAHBgUrDgMCGgQUXI3/vEvbfD7eUzpI1js5mj5OUC4EFCjw+OapyHfMQ0Xbmq7XOoOsDg+oAgcDrUjkAJSNgAAYDzIwMjEwNTE3MDYyMzAxWqARGA8yMDIxMDUxNzA2MjMwMVqhIzAhMB8GCSsGAQUFBzABAgQSBBDkdyImUBsO+Q8iAA2xbXu8MAkGByqGSM49BAEDRwAwRAIgW+JlwUmnZCVsME2kOyQlcqF01Lel/0nQdE6IaZmFADECIGhOH1k5Dzq42y2jCxZCzxevRc6vY1o8ky0Xy4DxLIWJoIICojCCAp4wggKaMIICQKADAgECAgcDrTZEREJrMAoGCCqGSM49BAMCMIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMB4XDTIwMDUwNjAwMDAwMFoXDTIzMDUwNjIzNTk1OVowVzELMAkGA1UEBhMCREUxGjAYBgNVBAoMEWdlbWF0aWsgTk9ULVZBTElEMSwwKgYDVQQDDCNPQ1NQIFNpZ25lciBLb21wLUNBMTAgZWNjIFRFU1QtT05MWTBaMBQGByqGSM49AgEGCSskAwMCCAEBBwNCAAQbB+RoQs3RyvkN+o/Vs2xZlLZeK4fqt4s9kscFIuTIWn9LNMq80N2bucqWno2iuDXPWeOHJqlGtpoLNFLpWt4Po4HHMIHEMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMA4GA1UdDwEB/wQEAwIGQDAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMBMGA1UdJQQMMAoGCCsGAQUFBwMJMAwGA1UdEwEB/wQCMAAwOAYIKwYBBQUHAQEELDAqMCgGCCsGAQUFBzABhhxodHRwOi8vZWhjYS5nZW1hdGlrLmRlL29jc3AvMB0GA1UdDgQWBBQcqomWuxucPpsAjIXZZJyse1SZ4jAKBggqhkjOPQQDAgNIADBFAiEAiR3T/gS0MtFGdvQHyaCa+XF6lisspf+WRUahfLQPrg4CICQ4KZc7AYkTFnHFGbh2In8Y/Nkjh5wCdpWqeKRgBBUJ"
        val ProducedAt = Instant.fromEpochSeconds(1621232581) // 2021-05-17T08:23:01.000+0200

        object SignerCert {
            val Base64 =
                "MIICmjCCAkCgAwIBAgIHA602RERCazAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMDA1MDYwMDAwMDBaFw0yMzA1MDYyMzU5NTlaMFcxCzAJBgNVBAYTAkRFMRowGAYDVQQKDBFnZW1hdGlrIE5PVC1WQUxJRDEsMCoGA1UEAwwjT0NTUCBTaWduZXIgS29tcC1DQTEwIGVjYyBURVNULU9OTFkwWjAUBgcqhkjOPQIBBgkrJAMDAggBAQcDQgAEGwfkaELN0cr5DfqP1bNsWZS2XiuH6reLPZLHBSLkyFp/SzTKvNDdm7nKlp6Norg1z1njhyapRraaCzRS6VreD6OBxzCBxDAfBgNVHSMEGDAWgBQo8Pjmqch3zENF25qu1zqDrA4PqDAOBgNVHQ8BAf8EBAMCBkAwFQYDVR0gBA4wDDAKBggqghQATASBIzATBgNVHSUEDDAKBggrBgEFBQcDCTAMBgNVHRMBAf8EAjAAMDgGCCsGAQUFBwEBBCwwKjAoBggrBgEFBQcwAYYcaHR0cDovL2VoY2EuZ2VtYXRpay5kZS9vY3NwLzAdBgNVHQ4EFgQUHKqJlrsbnD6bAIyF2WScrHtUmeIwCgYIKoZIzj0EAwIDSAAwRQIhAIkd0/4EtDLRRnb0B8mgmvlxepYrLKX/lkVGoXy0D64OAiAkOCmXOwGJExZxxRm4diJ/GPzZI4ecAnaVqnikYAQVCQ=="
            val X509Certificate by lazy { base64X509Certificate(Base64) }
        }
    }

    /**
     * Second response of [OCSP].
     */
    object OCSP2 {
        const val Base64 =
            "MIIEFgoBAKCCBA8wggQLBgkrBgEFBQcwAQEEggP8MIID+DCB+6FZMFcxCzAJBgNVBAYTAkRFMRowGAYDVQQKDBFnZW1hdGlrIE5PVC1WQUxJRDEsMCoGA1UEAwwjT0NTUCBTaWduZXIgS29tcC1DQTEwIGVjYyBURVNULU9OTFkYDzIwMjEwNTE3MDYyMzAxWjBoMGYwPjAHBgUrDgMCGgQUXI3/vEvbfD7eUzpI1js5mj5OUC4EFCjw+OapyHfMQ0Xbmq7XOoOsDg+oAgcBuyypCGo7gAAYDzIwMjEwNTE3MDYyMzAxWqARGA8yMDIxMDUxNzA2MjMwMVqhIzAhMB8GCSsGAQUFBzABAgQSBBDIsivTG9WljP4InmqVdKQmMAkGByqGSM49BAEDRwAwRAIgZMCyRhqMOaEG10KPz3mL5Yh7oX9fiIdBl8WrxLT2SewCIEvjzedVlnbt/j4e7VALo2xl8wvOcYe8gT04+PqH5vkfoIICojCCAp4wggKaMIICQKADAgECAgcDrTZEREJrMAoGCCqGSM49BAMCMIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMB4XDTIwMDUwNjAwMDAwMFoXDTIzMDUwNjIzNTk1OVowVzELMAkGA1UEBhMCREUxGjAYBgNVBAoMEWdlbWF0aWsgTk9ULVZBTElEMSwwKgYDVQQDDCNPQ1NQIFNpZ25lciBLb21wLUNBMTAgZWNjIFRFU1QtT05MWTBaMBQGByqGSM49AgEGCSskAwMCCAEBBwNCAAQbB+RoQs3RyvkN+o/Vs2xZlLZeK4fqt4s9kscFIuTIWn9LNMq80N2bucqWno2iuDXPWeOHJqlGtpoLNFLpWt4Po4HHMIHEMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMA4GA1UdDwEB/wQEAwIGQDAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMBMGA1UdJQQMMAoGCCsGAQUFBwMJMAwGA1UdEwEB/wQCMAAwOAYIKwYBBQUHAQEELDAqMCgGCCsGAQUFBzABhhxodHRwOi8vZWhjYS5nZW1hdGlrLmRlL29jc3AvMB0GA1UdDgQWBBQcqomWuxucPpsAjIXZZJyse1SZ4jAKBggqhkjOPQQDAgNIADBFAiEAiR3T/gS0MtFGdvQHyaCa+XF6lisspf+WRUahfLQPrg4CICQ4KZc7AYkTFnHFGbh2In8Y/Nkjh5wCdpWqeKRgBBUJ"
        val ProducedAt = Instant.fromEpochSeconds(1621232581) // 2021-05-17T08:23:01.000+0200
        val CertToCheckSerialNumber = "487275465566779" // IDP 2
    }

    /**
     * Third response of [OCSP].
     */
    object OCSP3 {
        const val Base64 =
            "MIIEFgoBAKCCBA8wggQLBgkrBgEFBQcwAQEEggP8MIID+DCB+6FZMFcxCzAJBgNVBAYTAkRFMRowGAYDVQQKDBFnZW1hdGlrIE5PVC1WQUxJRDEsMCoGA1UEAwwjT0NTUCBTaWduZXIgS29tcC1DQTEwIGVjYyBURVNULU9OTFkYDzIwMjEwNTE3MDYyMzAwWjBoMGYwPjAHBgUrDgMCGgQUXI3/vEvbfD7eUzpI1js5mj5OUC4EFCjw+OapyHfMQ0Xbmq7XOoOsDg+oAgcBPCti7yC3gAAYDzIwMjEwNTE3MDYyMzAwWqARGA8yMDIxMDUxNzA2MjMwMFqhIzAhMB8GCSsGAQUFBzABAgQSBBAWpjYsPzj/U96/S1MvypTWMAkGByqGSM49BAEDRwAwRAIgXfEC3h/1H2/aHGEyJY9L59S6NbqdkStBBk2vczj+3mwCIASMGDqPuhA7ZLBJ5HhHpwKYEQw/YPluyBMnz7j2dXtPoIICojCCAp4wggKaMIICQKADAgECAgcDrTZEREJrMAoGCCqGSM49BAMCMIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMB4XDTIwMDUwNjAwMDAwMFoXDTIzMDUwNjIzNTk1OVowVzELMAkGA1UEBhMCREUxGjAYBgNVBAoMEWdlbWF0aWsgTk9ULVZBTElEMSwwKgYDVQQDDCNPQ1NQIFNpZ25lciBLb21wLUNBMTAgZWNjIFRFU1QtT05MWTBaMBQGByqGSM49AgEGCSskAwMCCAEBBwNCAAQbB+RoQs3RyvkN+o/Vs2xZlLZeK4fqt4s9kscFIuTIWn9LNMq80N2bucqWno2iuDXPWeOHJqlGtpoLNFLpWt4Po4HHMIHEMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMA4GA1UdDwEB/wQEAwIGQDAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMBMGA1UdJQQMMAoGCCsGAQUFBwMJMAwGA1UdEwEB/wQCMAAwOAYIKwYBBQUHAQEELDAqMCgGCCsGAQUFBzABhhxodHRwOi8vZWhjYS5nZW1hdGlrLmRlL29jc3AvMB0GA1UdDgQWBBQcqomWuxucPpsAjIXZZJyse1SZ4jAKBggqhkjOPQQDAgNIADBFAiEAiR3T/gS0MtFGdvQHyaCa+XF6lisspf+WRUahfLQPrg4CICQ4KZc7AYkTFnHFGbh2In8Y/Nkjh5wCdpWqeKRgBBUJ"
        val ProducedAt = Instant.fromEpochSeconds(1621232580) // 2021-05-17T08:23:00.000+0200
        val CertToCheckSerialNumber = "347632017809591" //  VAU
    }

    /**
     * +- OCSP Response --------+
     * |                        |
     * | +-------------+        |  verify with  +--------------+  verify with  +--------------+
     * | | Certificate |--------|---------------| OCSP EE Cert |---------------| OCSP CA Cert |
     * | +-------------+        |               +--------------+               +--------------+
     * |                        |
     * | +- Single Response -+  |  equals  +--------------------+
     * | | Certificate ID    |--|----------| VAU/IDP CA Cert ID |
     * | +-------------------+  |          +--------------------+
     * |                        |
     * +------------------------+
     */
    object OCSP {
        @Suppress("MaxLineLength")
        val JsonOCSPList = """
            {
                "OCSP Responses": [
                    "MIIEFgoBAKCCBA8wggQLBgkrBgEFBQcwAQEEggP8MIID+DCB+6FZMFcxCzAJBgNVBAYTAkRFMRowGAYDVQQKDBFnZW1hdGlrIE5PVC1WQUxJRDEsMCoGA1UEAwwjT0NTUCBTaWduZXIgS29tcC1DQTEwIGVjYyBURVNULU9OTFkYDzIwMjEwNTE3MDYyMzAxWjBoMGYwPjAHBgUrDgMCGgQUXI3/vEvbfD7eUzpI1js5mj5OUC4EFCjw+OapyHfMQ0Xbmq7XOoOsDg+oAgcDrUjkAJSNgAAYDzIwMjEwNTE3MDYyMzAxWqARGA8yMDIxMDUxNzA2MjMwMVqhIzAhMB8GCSsGAQUFBzABAgQSBBDkdyImUBsO+Q8iAA2xbXu8MAkGByqGSM49BAEDRwAwRAIgW+JlwUmnZCVsME2kOyQlcqF01Lel/0nQdE6IaZmFADECIGhOH1k5Dzq42y2jCxZCzxevRc6vY1o8ky0Xy4DxLIWJoIICojCCAp4wggKaMIICQKADAgECAgcDrTZEREJrMAoGCCqGSM49BAMCMIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMB4XDTIwMDUwNjAwMDAwMFoXDTIzMDUwNjIzNTk1OVowVzELMAkGA1UEBhMCREUxGjAYBgNVBAoMEWdlbWF0aWsgTk9ULVZBTElEMSwwKgYDVQQDDCNPQ1NQIFNpZ25lciBLb21wLUNBMTAgZWNjIFRFU1QtT05MWTBaMBQGByqGSM49AgEGCSskAwMCCAEBBwNCAAQbB+RoQs3RyvkN+o/Vs2xZlLZeK4fqt4s9kscFIuTIWn9LNMq80N2bucqWno2iuDXPWeOHJqlGtpoLNFLpWt4Po4HHMIHEMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMA4GA1UdDwEB/wQEAwIGQDAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMBMGA1UdJQQMMAoGCCsGAQUFBwMJMAwGA1UdEwEB/wQCMAAwOAYIKwYBBQUHAQEELDAqMCgGCCsGAQUFBzABhhxodHRwOi8vZWhjYS5nZW1hdGlrLmRlL29jc3AvMB0GA1UdDgQWBBQcqomWuxucPpsAjIXZZJyse1SZ4jAKBggqhkjOPQQDAgNIADBFAiEAiR3T/gS0MtFGdvQHyaCa+XF6lisspf+WRUahfLQPrg4CICQ4KZc7AYkTFnHFGbh2In8Y/Nkjh5wCdpWqeKRgBBUJ",
                    "MIIEFgoBAKCCBA8wggQLBgkrBgEFBQcwAQEEggP8MIID+DCB+6FZMFcxCzAJBgNVBAYTAkRFMRowGAYDVQQKDBFnZW1hdGlrIE5PVC1WQUxJRDEsMCoGA1UEAwwjT0NTUCBTaWduZXIgS29tcC1DQTEwIGVjYyBURVNULU9OTFkYDzIwMjEwNTE3MDYyMzAxWjBoMGYwPjAHBgUrDgMCGgQUXI3/vEvbfD7eUzpI1js5mj5OUC4EFCjw+OapyHfMQ0Xbmq7XOoOsDg+oAgcBuyypCGo7gAAYDzIwMjEwNTE3MDYyMzAxWqARGA8yMDIxMDUxNzA2MjMwMVqhIzAhMB8GCSsGAQUFBzABAgQSBBDIsivTG9WljP4InmqVdKQmMAkGByqGSM49BAEDRwAwRAIgZMCyRhqMOaEG10KPz3mL5Yh7oX9fiIdBl8WrxLT2SewCIEvjzedVlnbt/j4e7VALo2xl8wvOcYe8gT04+PqH5vkfoIICojCCAp4wggKaMIICQKADAgECAgcDrTZEREJrMAoGCCqGSM49BAMCMIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMB4XDTIwMDUwNjAwMDAwMFoXDTIzMDUwNjIzNTk1OVowVzELMAkGA1UEBhMCREUxGjAYBgNVBAoMEWdlbWF0aWsgTk9ULVZBTElEMSwwKgYDVQQDDCNPQ1NQIFNpZ25lciBLb21wLUNBMTAgZWNjIFRFU1QtT05MWTBaMBQGByqGSM49AgEGCSskAwMCCAEBBwNCAAQbB+RoQs3RyvkN+o/Vs2xZlLZeK4fqt4s9kscFIuTIWn9LNMq80N2bucqWno2iuDXPWeOHJqlGtpoLNFLpWt4Po4HHMIHEMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMA4GA1UdDwEB/wQEAwIGQDAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMBMGA1UdJQQMMAoGCCsGAQUFBwMJMAwGA1UdEwEB/wQCMAAwOAYIKwYBBQUHAQEELDAqMCgGCCsGAQUFBzABhhxodHRwOi8vZWhjYS5nZW1hdGlrLmRlL29jc3AvMB0GA1UdDgQWBBQcqomWuxucPpsAjIXZZJyse1SZ4jAKBggqhkjOPQQDAgNIADBFAiEAiR3T/gS0MtFGdvQHyaCa+XF6lisspf+WRUahfLQPrg4CICQ4KZc7AYkTFnHFGbh2In8Y/Nkjh5wCdpWqeKRgBBUJ",
                    "MIIEFgoBAKCCBA8wggQLBgkrBgEFBQcwAQEEggP8MIID+DCB+6FZMFcxCzAJBgNVBAYTAkRFMRowGAYDVQQKDBFnZW1hdGlrIE5PVC1WQUxJRDEsMCoGA1UEAwwjT0NTUCBTaWduZXIgS29tcC1DQTEwIGVjYyBURVNULU9OTFkYDzIwMjEwNTE3MDYyMzAwWjBoMGYwPjAHBgUrDgMCGgQUXI3/vEvbfD7eUzpI1js5mj5OUC4EFCjw+OapyHfMQ0Xbmq7XOoOsDg+oAgcBPCti7yC3gAAYDzIwMjEwNTE3MDYyMzAwWqARGA8yMDIxMDUxNzA2MjMwMFqhIzAhMB8GCSsGAQUFBzABAgQSBBAWpjYsPzj/U96/S1MvypTWMAkGByqGSM49BAEDRwAwRAIgXfEC3h/1H2/aHGEyJY9L59S6NbqdkStBBk2vczj+3mwCIASMGDqPuhA7ZLBJ5HhHpwKYEQw/YPluyBMnz7j2dXtPoIICojCCAp4wggKaMIICQKADAgECAgcDrTZEREJrMAoGCCqGSM49BAMCMIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJRDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMB4XDTIwMDUwNjAwMDAwMFoXDTIzMDUwNjIzNTk1OVowVzELMAkGA1UEBhMCREUxGjAYBgNVBAoMEWdlbWF0aWsgTk9ULVZBTElEMSwwKgYDVQQDDCNPQ1NQIFNpZ25lciBLb21wLUNBMTAgZWNjIFRFU1QtT05MWTBaMBQGByqGSM49AgEGCSskAwMCCAEBBwNCAAQbB+RoQs3RyvkN+o/Vs2xZlLZeK4fqt4s9kscFIuTIWn9LNMq80N2bucqWno2iuDXPWeOHJqlGtpoLNFLpWt4Po4HHMIHEMB8GA1UdIwQYMBaAFCjw+OapyHfMQ0Xbmq7XOoOsDg+oMA4GA1UdDwEB/wQEAwIGQDAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMBMGA1UdJQQMMAoGCCsGAQUFBwMJMAwGA1UdEwEB/wQCMAAwOAYIKwYBBQUHAQEELDAqMCgGCCsGAQUFBzABhhxodHRwOi8vZWhjYS5nZW1hdGlrLmRlL29jc3AvMB0GA1UdDgQWBBQcqomWuxucPpsAjIXZZJyse1SZ4jAKBggqhkjOPQQDAgNIADBFAiEAiR3T/gS0MtFGdvQHyaCa+XF6lisspf+WRUahfLQPrg4CICQ4KZc7AYkTFnHFGbh2In8Y/Nkjh5wCdpWqeKRgBBUJ"
                ]
            }
        """.trimIndent()

        val OCSPList: UntrustedOCSPList by lazy { Json.decodeFromString(JsonOCSPList) }
    }

    object RCA3 {
        private val data = """
            -----BEGIN CERTIFICATE-----
            MIICkzCCAjmgAwIBAgIBATAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
            BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
            IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
            TS5SQ0EzIFRFU1QtT05MWTAeFw0xNzA4MTEwODM4NDVaFw0yNzA4MDkwODM4NDVa
            MIGBMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
            RDE0MDIGA1UECwwrWmVudHJhbGUgUm9vdC1DQSBkZXIgVGVsZW1hdGlraW5mcmFz
            dHJ1a3R1cjEbMBkGA1UEAwwSR0VNLlJDQTMgVEVTVC1PTkxZMFowFAYHKoZIzj0C
            AQYJKyQDAwIIAQEHA0IABG+raY8OSxIEfrDwz4K4K1HXLXbd0ZzAKtD9SUDtSexn
            fsai8lkY8rM59TLky//HB8QDkyZewRPXClwpXCrj5HOjgZ4wgZswHQYDVR0OBBYE
            FAeQMy11U15/+Mg3v37JJldo3zjSMEIGCCsGAQUFBwEBBDYwNDAyBggrBgEFBQcw
            AYYmaHR0cDovL29jc3Aucm9vdC1jYS50aS1kaWVuc3RlLmRlL29jc3AwDwYDVR0T
            AQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwFQYDVR0gBA4wDDAKBggqghQATASB
            IzAKBggqhkjOPQQDAgNIADBFAiEAo4kNteSBVR4ovNeTBhkiSXsWzdRC0tQeMfIt
            sE0s7/8CIDZ3EQxclVBV3huM8Bzl9ePbNsV+Lvnjv+Fo1om5+xJ2
            -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object TrustAnchorRCA3 {
        private val data = """
           -----BEGIN CERTIFICATE-----
            MIICkzCCAjmgAwIBAgIBATAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
            BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
            IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
            TS5SQ0EzIFRFU1QtT05MWTAeFw0xNzA4MTEwODM4NDVaFw0yNzA4MDkwODM4NDVa
            MIGBMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
            RDE0MDIGA1UECwwrWmVudHJhbGUgUm9vdC1DQSBkZXIgVGVsZW1hdGlraW5mcmFz
            dHJ1a3R1cjEbMBkGA1UEAwwSR0VNLlJDQTMgVEVTVC1PTkxZMFowFAYHKoZIzj0C
            AQYJKyQDAwIIAQEHA0IABG+raY8OSxIEfrDwz4K4K1HXLXbd0ZzAKtD9SUDtSexn
            fsai8lkY8rM59TLky//HB8QDkyZewRPXClwpXCrj5HOjgZ4wgZswHQYDVR0OBBYE
            FAeQMy11U15/+Mg3v37JJldo3zjSMEIGCCsGAQUFBwEBBDYwNDAyBggrBgEFBQcw
            AYYmaHR0cDovL29jc3Aucm9vdC1jYS50aS1kaWVuc3RlLmRlL29jc3AwDwYDVR0T
            AQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwFQYDVR0gBA4wDDAKBggqghQATASB
            IzAKBggqhkjOPQQDAgNIADBFAiEAo4kNteSBVR4ovNeTBhkiSXsWzdRC0tQeMfIt
            sE0s7/8CIDZ3EQxclVBV3huM8Bzl9ePbNsV+Lvnjv+Fo1om5+xJ2
            -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object TrustAnchorRCA3Invalid {
        private val data = """
            -----BEGIN CERTIFICATE-----
            MIIDYDCCAkigAwIBAgIUUnQ6d1ZcA0I1VNMeG42Q+iLxcDYwDQYJKoZIhvcNAQEL
            BQAwQTEbMBkGA1UEAwwSR0VNLlJDQTMgVEVTVC1PTkxZMRUwEwYDVQQKDAxnZW1h
            dGlrIEdtYkgxCzAJBgNVBAYTAkRFMB4XDTI1MDcyOTEzNTkyMloXDTMwMDcyODEz
            NTkyMlowQTEbMBkGA1UEAwwSR0VNLlJDQTQgVEVTVC1PTkxZMRUwEwYDVQQKDAxn
            ZW1hdGlrIEdtYkgxCzAJBgNVBAYTAkRFMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
            MIIBCgKCAQEAwEOxCaI5UGNWhPQBWAdfC9g12OugRiA6NL5rWVQefHwPQicpRZkH
            dqHvHk/aW3LWpIW1kuVgPF+AQTwLG5swIL6qGut0AVvktSwHqb2TnsqM1diWiV2n
            kb31cmy2D6QGxI8iBfI9Z9/C03zUvpA7ko/2pam/GSXdWPU3cekEGhX4b9aBK6cg
            FQrQLU1e/tD71thLZhonLKrTaqubfAZUXV4QkilgAA6vNPZ71mrbTx3GYaUaiza2
            eq1YqK/MVX/dTSTshnkMRbpxtgEYwsigcVrS5dl9DoUlbVglTvE9VIMjRcp1nUrO
            tVcnSgMZ5XD1zTi0/uN9shjOcLD1C+3OAwIDAQABo1AwTjAMBgNVHRMEBTADAQH/
            MB0GA1UdDgQWBBTxpcwJdB1Is9vn6YLXysYJoaMn4DAfBgNVHSMEGDAWgBSXGD1y
            TYoo0Y6jJI505UoVrVUm+jANBgkqhkiG9w0BAQsFAAOCAQEAgmN7VBqN5Fr1c38q
            SnG5D4uf3p1rsXhoRVu/7DSRvpDbAoxuZbncomuNFnBAcnrg58/7q9Mc8W6KzwL1
            iAmaYRoIMP5GnfhhFasu+cw/0LL1o0aFyUhABErM4hTIN/kCLZP71W8noT343Mpm
            bX4nejLx0fODwjxCIgnyIhboM/yFuFDPWaIUP2Zk2CvidH2hGlnZdg5yr3wL7eV+
            OS1EzA2CN06s9odl0jQC62kKNKY4JKY99DVCSycRLOMNDDXlHdnp0M1aB06zTO59
            cjLK3oHSv3gd9gRrG3UeLM+rGJV+31GhAZQzijjMzRcl5/yUo5gRS8Oy905bvGLn
            RewtJQ==
            -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object RCA4CrossSignedByRCA3 {
        private val data = """
            -----BEGIN CERTIFICATE-----
            MIICtDCCAlqgAwIBAgIBKzAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
            BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
            IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
            TS5SQ0EzIFRFU1QtT05MWTAeFw0xOTA4MDcxMDE3MjdaFw0yNzA4MDkwODM4NDVa
            MIGBMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
            RDE0MDIGA1UECwwrWmVudHJhbGUgUm9vdC1DQSBkZXIgVGVsZW1hdGlraW5mcmFz
            dHJ1a3R1cjEbMBkGA1UEAwwSR0VNLlJDQTQgVEVTVC1PTkxZMFowFAYHKoZIzj0C
            AQYJKyQDAwIIAQEHA0IABD2om+MtwPSn89HGErbYvxjoWRwHoO/JJXf51n8L/Nsd
            PjZUIVrveL/ydaJJZNaEx4syq/O5e8Q5WkEFB8kbm5Sjgb8wgbwwHQYDVR0OBBYE
            FFHb2WZCs0orP1csVI2Fcx3nV89/MB8GA1UdIwQYMBaAFAeQMy11U15/+Mg3v37J
            Jldo3zjSMEIGCCsGAQUFBwEBBDYwNDAyBggrBgEFBQcwAYYmaHR0cDovL29jc3Au
            cm9vdC1jYS50aS1kaWVuc3RlLmRlL29jc3AwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
            HQ8BAf8EBAMCAQYwFQYDVR0gBA4wDDAKBggqghQATASBIzAKBggqhkjOPQQDAgNI
            ADBFAiEAi3HsZud766MjjCBamvjY0PJ9nSNhWEgO3dv+3CRZbvwCIF/Ftch7+izD
            9L7Q/BhqlxS9Pr5Zv6nBDjbUze6qzuNv
            -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object RCA5CrossSignedByRCA4 {
        private val data = """
        -----BEGIN CERTIFICATE-----
        MIIC7DCCApOgAwIBAgIBKTAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
        BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
        IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
        TS5SQ0E0IFRFU1QtT05MWTAeFw0yMTA3MjMxMTMyNDlaFw0yOTA4MDQxMDE0NDZa
        MIGBMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
        RDE0MDIGA1UECwwrWmVudHJhbGUgUm9vdC1DQSBkZXIgVGVsZW1hdGlraW5mcmFz
        dHJ1a3R1cjEbMBkGA1UEAwwSR0VNLlJDQTUgVEVTVC1PTkxZMFowFAYHKoZIzj0C
        AQYJKyQDAwIIAQEHA0IABJukjjeYlo6B3WTeNVof861qQRIa3ZcAkUyj1zMER6I+
        aley7K/U1XCFQ72ADk9qoRAYNspYA1dVQiFsXML32PWjgfgwgfUwHQYDVR0OBBYE
        FOGt4Af80iB5JPTcl70yZM1rFIUJMB8GA1UdIwQYMBaAFFHb2WZCs0orP1csVI2F
        cx3nV89/MEoGCCsGAQUFBwEBBD4wPDA6BggrBgEFBQcwAYYuaHR0cDovL29jc3At
        dGVzdHJlZi5yb290LWNhLnRpLWRpZW5zdGUuZGUvb2NzcDAOBgNVHQ8BAf8EBAMC
        AQYwRgYDVR0gBD8wPTA7BggqghQATASBIzAvMC0GCCsGAQUFBwIBFiFodHRwOi8v
        d3d3LmdlbWF0aWsuZGUvZ28vcG9saWNpZXMwDwYDVR0TAQH/BAUwAwEB/zAKBggq
        hkjOPQQDAgNHADBEAiAryU2k1dZAABPmVWBJtxjNooi1421TIilqn1vqztaG6wIg
        ajX6VL8Kek6S3L6B55WX5wxv9a20NtzbI4/nSF4LlPE=
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object CA51 {
        private val data = """
        -----BEGIN CERTIFICATE-----
        MIIC8jCCApmgAwIBAgIBETAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
        BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
        IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
        TS5SQ0E1IFRFU1QtT05MWTAeFw0yMTExMDgxNDM0MjlaFw0yOTExMDYxNDM0Mjha
        MIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
        RDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3Ry
        dWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBNTEgVEVTVC1PTkxZMFowFAYHKoZI
        zj0CAQYJKyQDAwIIAQEHA0IABCoS/ur5bCfiASFop+62agb9x27NtxpfES9qEMNI
        YCV+CkmSDZTltn4tENgRWMO7fBuGA5l/NcKRAerLd88cWB+jgfswgfgwHQYDVR0O
        BBYEFGKVu+5G2Sov8unIzGyXJNRVlTF3MB8GA1UdIwQYMBaAFOGt4Af80iB5JPTc
        l70yZM1rFIUJMEoGCCsGAQUFBwEBBD4wPDA6BggrBgEFBQcwAYYuaHR0cDovL29j
        c3AtdGVzdHJlZi5yb290LWNhLnRpLWRpZW5zdGUuZGUvb2NzcDAOBgNVHQ8BAf8E
        BAMCAQYwRgYDVR0gBD8wPTA7BggqghQATASBIzAvMC0GCCsGAQUFBwIBFiFodHRw
        Oi8vd3d3LmdlbWF0aWsuZGUvZ28vcG9saWNpZXMwEgYDVR0TAQH/BAgwBgEB/wIB
        ADAKBggqhkjOPQQDAgNHADBEAiBxWVtueiCPZ1A5xFZutehkJg019HwbN8bA6VBm
        3zcCUQIgHVb2mgvU2Rlw2l2ZmLcoNqoqBpwRWpeM6u35ztGxNMM=
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object CA10 {
        private val data = """
       -----BEGIN CERTIFICATE-----
        MIIDGjCCAr+gAwIBAgIBFzAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
        BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
        IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
        TS5SQ0EzIFRFU1QtT05MWTAeFw0xNzA4MzAxMTM2MjJaFw0yNTA4MjgxMTM2MjFa
        MIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
        RDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3Ry
        dWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTAgVEVTVC1PTkxZMFowFAYHKoZI
        zj0CAQYJKyQDAwIIAQEHA0IABDFinQgzfsT1CN0QWwdm7e2JiaDYHocCiy1TWpOP
        yHwoPC54RULeUIBJeX199Qm1FFpgeIRP1E8cjbHGNsRbju6jggEgMIIBHDAdBgNV
        HQ4EFgQUKPD45qnId8xDRduartc6g6wOD6gwHwYDVR0jBBgwFoAUB5AzLXVTXn/4
        yDe/fskmV2jfONIwQgYIKwYBBQUHAQEENjA0MDIGCCsGAQUFBzABhiZodHRwOi8v
        b2NzcC5yb290LWNhLnRpLWRpZW5zdGUuZGUvb2NzcDASBgNVHRMBAf8ECDAGAQH/
        AgEAMA4GA1UdDwEB/wQEAwIBBjAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMFsGA1Ud
        EQRUMFKgUAYDVQQKoEkMR2dlbWF0aWsgR2VzZWxsc2NoYWZ0IGbDvHIgVGVsZW1h
        dGlrYW53ZW5kdW5nZW4gZGVyIEdlc3VuZGhlaXRza2FydGUgbWJIMAoGCCqGSM49
        BAMCA0kAMEYCIQCprLtIIRx1Y4mKHlNngOVAf6D7rkYSa723oRyX7J2qwgIhAKPi
        9GSJyYp4gMTFeZkqvj8pcAqxNR9UKV7UYBlHrdxC
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object CA11 {
        private val data = """
       -----BEGIN CERTIFICATE-----
        MIIDGDCCAr+gAwIBAgIBFjAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
        BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
        IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
        TS5SQ0EzIFRFU1QtT05MWTAeFw0xNzA4MzAxMTM2MDhaFw0yNTA4MjgxMTM2MDda
        MIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
        RDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3Ry
        dWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBMTEgVEVTVC1PTkxZMFowFAYHKoZI
        zj0CAQYJKyQDAwIIAQEHA0IABGTK1hKec85JygijmQ2crZYDrpMqbxX73b9BUDQ/
        b/zHoa1Liq6icJKrlCFTjJ1J7EAaAxLsGG0N/XjxWSxlBIGjggEgMIIBHDAdBgNV
        HQ4EFgQUTBRlQvR625Hnyqqo6Q4ezy2L57owHwYDVR0jBBgwFoAUB5AzLXVTXn/4
        yDe/fskmV2jfONIwQgYIKwYBBQUHAQEENjA0MDIGCCsGAQUFBzABhiZodHRwOi8v
        b2NzcC5yb290LWNhLnRpLWRpZW5zdGUuZGUvb2NzcDASBgNVHRMBAf8ECDAGAQH/
        AgEAMA4GA1UdDwEB/wQEAwIBBjAVBgNVHSAEDjAMMAoGCCqCFABMBIEjMFsGA1Ud
        EQRUMFKgUAYDVQQKoEkMR2dlbWF0aWsgR2VzZWxsc2NoYWZ0IGbDvHIgVGVsZW1h
        dGlrYW53ZW5kdW5nZW4gZGVyIEdlc3VuZGhlaXRza2FydGUgbWJIMAoGCCqGSM49
        BAMCA0cAMEQCIHNbTALWZyWkNTfmVHlADw7lmjF/mPgk4cT0iIavuddAAiBqcZFt
        l2T02k5YDqltLug2EYy+naFfl3gEI+qCS7fsAg==
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object CA11Invlid {
        private val data = """
       -----BEGIN CERTIFICATE-----
        MIIC8jCCApmgAwIBAgIBETAKBggqhkjOPQQDAjCBgTELMAkGA1UEBhMCREUxHzAd
        BgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxNDAyBgNVBAsMK1plbnRyYWxl
        IFJvb3QtQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3RydWt0dXIxGzAZBgNVBAMMEkdF
        TS5SQ0E1IFRFU1QtT05MWTAeFw0yMTExMDgxNDM0MjlaFw0yOTExMDYxNDM0Mjha
        MIGEMQswCQYDVQQGEwJERTEfMB0GA1UECgwWZ2VtYXRpayBHbWJIIE5PVC1WQUxJ
        RDEyMDAGA1UECwwpS29tcG9uZW50ZW4tQ0EgZGVyIFRlbGVtYXRpa2luZnJhc3Ry
        dWt0dXIxIDAeBgNVBAMMF0dFTS5LT01QLUNBNTEgVEVTVC1PTkxZMFowFAYHKoZI
        zj0CAQYJKyQDAwIIAQEHA0IABCoS/ur5bCfiASFop+62agb9x27NtxpfES9qEMNI
        YCV+CkmSDZTltn4tENgRWMO7fBuGA5l/NcKRAerLd88cWB+jgfswgfgwHQYDVR0O
        BBYEFGKVu+5G2Sov8unIzGyXJNRVlTF3MB8GA1UdIwQYMBaAFOGt4Af80iB5JPTc
        l70yZM1rFIUJMEoGCCsGAQUFBwEBBD4wPDA6BggrBgEFBQcwAYYuaHR0cDovL29j
        c3AtdGVzdHJlZi5yb290LWNhLnRpLWRpZW5zdGUuZGUvb2NzcDAOBgNVHQ8BAf8E
        BAMCAQYwRgYDVR0gBD8wPTA7BggqghQATASBIzAvMC0GCCsGAQUFBwIBFiFodHRw
        Oi8vd3d3LmdlbWF0aWsuZGUvZ28vcG9saWNpZXMwEgYDVR0TAQH/BAgwBgEB/wIB
        ADAKBggqhkjOPQQDAgNHADBEAiBxWVtueiCPZ1A5xFZutehkJg019HwbN8bA6VBm
        3zcCUQIgHVb2mgvU2Rlw2l2ZmLcoNqoqBpwRWpeM6u35ztGxXYZ=
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object Ee1 {
        private val data = """
       -----BEGIN CERTIFICATE-----
        MIIDFTCCArygAwIBAgIHA+hRphBS2TAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMC
        REUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtv
        bXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQD
        DBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0xOTA1MjcyMjAwMDBaFw0yNDA1
        MjcyMTU5NTlaMIGJMQswCQYDVQQGEwJERTEmMCQGA1UECgwdZ2VtYXRpayBURVNU
        LU9OTFkgLSBOT1QtVkFMSUQxUjBQBgNVBAMMSVZlcnRyYXVlbnN3w7xyZGlnZSBB
        dXNmw7xocnVuZ3N1bWdlYnVuZyBmw7xyIGRhcyBadWdhbmdzZ2F0ZXdheSBURVNU
        LU9OTFkwWjAUBgcqhkjOPQIBBgkrJAMDAggBAQcDQgAEVThpYDCilFUOO8ibUeaT
        5ONjlgzUPDCAhksLotXZlwcWR5nUnV0d43b7GS98+AAoValeDraQBIQO/bAww6KN
        IKOCAQ8wggELMDgGCCsGAQUFBwEBBCwwKjAoBggrBgEFBQcwAYYcaHR0cDovL2Vo
        Y2EuZ2VtYXRpay5kZS9vY3NwLzAfBgNVHSMEGDAWgBQo8Pjmqch3zENF25qu1zqD
        rA4PqDAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFJFl974yB8Z7zsIOb2Tnm2yL
        WeKhMCEGA1UdIAQaMBgwCgYIKoIUAEwEgRswCgYIKoIUAEwEgSMwDAYDVR0TAQH/
        BAIwADBOBgUrJAgDAwRFMEMwQTA/MD0wOzAtDCtlUEEgdmVydHJhdWVuc3fDvHJk
        aWdlIEF1c2bDvGhydW5nc3VtZ2VidW5nMAoGCCqCFABMBIFRMAoGCCqGSM49BAMC
        A0cAMEQCIDZcjnOmpelaAI/jrtAWANywuaoIhO8I/XRobPV5ucHsAiBGyec/0Giq
        uTcE3gAtuG9GBhCFuwaiese2yuub9gth9w==
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object Ee2 {
        private val data = """
       -----BEGIN CERTIFICATE-----
        MIICsTCCAligAwIBAgIHA61I5ACUjTAKBggqhkjOPQQDAjCBhDELMAkGA1UEBhMCREUxHzAdBgNVBAoMFmdlbWF0aWsgR21iSCBOT1QtVkFMSUQxMjAwBgNVBAsMKUtvbXBvbmVudGVuLUNBIGRlciBUZWxlbWF0aWtpbmZyYXN0cnVrdHVyMSAwHgYDVQQDDBdHRU0uS09NUC1DQTEwIFRFU1QtT05MWTAeFw0yMDA4MDQwMDAwMDBaFw0yNTA4MDQyMzU5NTlaMEkxCzAJBgNVBAYTAkRFMSYwJAYDVQQKDB1nZW1hdGlrIFRFU1QtT05MWSAtIE5PVC1WQUxJRDESMBAGA1UEAwwJSURQIFNpZyAxMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABJZQrG1NWxIB3kz/6Z2zojlkJqN3vJXZ3EZnJ6JXTXw5ZDFZ5XjwWmtgfomv3VOV7qzI5ycUSJysMWDEu3mqRcajge0wgeowHQYDVR0OBBYEFJ8DVLAZWT+BlojTD4MT/Na+ES8YMDgGCCsGAQUFBwEBBCwwKjAoBggrBgEFBQcwAYYcaHR0cDovL2VoY2EuZ2VtYXRpay5kZS9vY3NwLzAMBgNVHRMBAf8EAjAAMCEGA1UdIAQaMBgwCgYIKoIUAEwEgUswCgYIKoIUAEwEgSMwHwYDVR0jBBgwFoAUKPD45qnId8xDRduartc6g6wOD6gwLQYFKyQIAwMEJDAiMCAwHjAcMBowDAwKSURQLURpZW5zdDAKBggqghQATASCBDAOBgNVHQ8BAf8EBAMCB4AwCgYIKoZIzj0EAwIDRwAwRAIgVBPhAwyX8HAVH0O0b3+VazpBAWkQNjkEVRkv+EYX1e8CIFdn4O+nivM+XVi9xiKK4dW1R7MD334OpOPTFjeEhIVV
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }

    object Ee3 {
        private val data = """
       -----BEGIN CERTIFICATE-----
        MIICWzCCAgKgAwIBAgIUXcN6K1n5kgykxETzVBv/WoRt01YwCgYIKoZIzj0EAwIwgYIxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJlcmxpbjEQMA4GA1UECgwHZ2VtYXRpazEQMA4GA1UECwwHZ2VtYXRpazEtMCsGA1UEAwwkRS1SZXplcHQtVkFVIEJlaXNwaWVsaW1wbGVtZW50aWVydW5nMB4XDTIwMDUyMjE2NTgyNFoXDTIxMDUyMjE2NTgyNFowgYIxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJlcmxpbjEQMA4GA1UECgwHZ2VtYXRpazEQMA4GA1UECwwHZ2VtYXRpazEtMCsGA1UEAwwkRS1SZXplcHQtVkFVIEJlaXNwaWVsaW1wbGVtZW50aWVydW5nMFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABIY0ISgw2tRXygUwXmaHE0FmucIaZf/r9VX05137BIiIZuS2hDYky9pDyX6omWi8Qf1TV2+CwD76fWAbn6ysKymjUzBRMB0GA1UdDgQWBBQh8MUVY5pJH8c0O/RVpDOPUIMXLjAfBgNVHSMEGDAWgBQh8MUVY5pJH8c0O/RVpDOPUIMXLjAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIC8jRqHV/dHK+N9Y0NF5MVHS2RvtP3ndzCPhwKBz0UW9AiA6oJnHJ2OP68rqpnbHG1/WWGJEfVT9Fig3zeYwYZKYvg==
        -----END CERTIFICATE-----
        """.trimIndent()
        val Base64 by lazy { x509PEMCertificateAsBase64(data) }
        val X509Certificate by lazy { x509Certificate(data) }
    }
    val TestTimestamp = Instant.fromEpochSeconds(1652778181) // 2022-05-17T08:23:01.000+0200
}

object TestCrypto {
    const val CertPublicKeyX = "8634212830dad457ca05305e6687134166b9c21a65ffebf555f4e75dfb048888"
    const val CertPublicKeyY = "66e4b6843624cbda43c97ea89968bc41fd53576f82c03efa7d601b9facac2b29"

    const val Message = "Hallo Test"

    const val EccPrivateKey = "5bbba34d47502bd588ed680dfa2309ca375eb7a35ddbbd67cc7f8b6b687a1c1d"
    const val EphemeralPublicKeyX =
        "754e548941e5cd073fed6d734578a484be9f0bbfa1b6fa3168ed7ffb22878f0f"
    const val EphemeralPublicKeyY =
        "9aef9bbd932a020d8828367bd080a3e72b36c41ee40c87253f9b1b0beb8371bf"

    const val IVBytes = "257db4604af8ae0dfced37ce"
    val CipherText =
        "01 754e548941e5cd073fed6d734578a484be9f0bbfa1b6fa3168ed7ffb22878f0f 9aef9bbd932a020d8828367bd080a3e72b36c41ee40c87253f9b1b0beb8371bf 257db4604af8ae0dfced37ce 86c2b491c7a8309e750b 4e6e307219863938c204dfe85502ee0a".replace(
            " ",
            ""
        )
}
