/*
 * Copyright (Change Date see Readme), gematik GmbH
 *
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the
 * European Commission – subsequent versions of the EUPL (the "Licence").
 * You may not use this work except in compliance with the Licence.
 *
 * You find a copy of the Licence in the "Licence" file or at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
 * In case of changes by gematik GmbH find details in the "Readme" file.
 *
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik find details in the "Readme" file.
 */

package de.gematik.ti.erp.app.database.realm.v1.euredeem

import de.gematik.ti.erp.app.database.realm.utils.toRealmInstant
import de.gematik.ti.erp.app.database.realm.v1.euredeem.EuTaskEventLogFactory.generateId
import kotlinx.datetime.Clock
import kotlinx.datetime.Instant
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime
import java.util.UUID
import kotlin.random.Random

/**
 * Factory object for creating EU redemption event entities.
 *
 * This factory provides convenient methods to create different types of events that occur
 * during the EU prescription redemption process. Each event tracks important state changes
 * such as access code creation, task redemption, expiration, etc.
 *
 * ## Event Types Supported:
 * - Access code creation and recreation
 * - Access code deletion
 * - Task redemption, expiration, and addition
 *
 * ## Event ID Generation:
 * All events are assigned a unique ID using the pattern:
 * `evt_{orderId}_{taskId}_{timestamp}_{random}`
 *
 * This ensures each event can be uniquely identified and traced in the system.
 *
 * @see de.gematik.ti.erp.app.database.realm.v1.euredeem.EuTaskEventLogEntityV1
 */
object EuTaskEventLogFactory {

    /**
     * Helper method to construct a list of [de.gematik.ti.erp.app.database.realm.v1.euredeem.EuTaskEventLogEntityV1] instance.
     *
     * This method encapsulates the common logic for creating event entities and ensures
     * consistent initialization of all event properties. It's used internally by all
     * public factory methods.
     *
     * ## Why this method exists:
     * - Reduces code duplication across factory methods
     * - Ensures all events are created with the same structure
     * - Makes it easier to add new event properties in the future
     *
     * @param id Unique identifier for this event (generated by [generateId])
     * @param orderId The redemption order this event belongs to
     * @param taskIds this event is associated with a task and is linked by its id
     * @param event The type of event being created (see [de.gematik.ti.erp.app.eurezept.model.EuEventType])
     * @param createdAt When this event was created (as [io.realm.kotlin.types.RealmInstant])
     * @return A fully initialized list of [de.gematik.ti.erp.app.database.realm.v1.euredeem.EuTaskEventLogEntityV1] instance
     */
    fun buildEvents(
        orderId: String,
        taskIds: List<String> = emptyList(),
        event: String,
        createdAt: Instant = Clock.System.now()
    ): List<EuTaskEventLogEntityV1> {
        return taskIds.map { taskId ->
            EuTaskEventLogEntityV1().apply {
                this.id = UUID.randomUUID().toString()
                this.orderId = orderId
                this.taskId = taskId
                this.createdAt = createdAt.toRealmInstant()
                this.event = event
            }
        }
    }

    /**
     * Generates a unique identifier for an event.
     *
     * The generated ID follows this pattern:
     * ```
     * evt_{orderId}_{taskId}_{timestamp}_{random}
     * ```
     *
     * ## ID Components:
     * - **evt_**: Prefix to identify this as an event ID
     * - **orderId**: The redemption order identifier
     * - **taskId**: (Optional) The prescription task identifier, included only if not null/empty
     * - **timestamp**: Current UTC time in format `YYYYMMDDTHHmmss`
     * - **random**: 16 character hexadecimal string for uniqueness
     *
     * ## Example IDs:
     * ```
     * evt_order123_task456_20231115T143022_a1b2c3d4e5f67890
     * evt_order789_20231115T143022_f9e8d7c6b5a43210  (without taskId)
     * ```
     *
     * ## Why we need unique IDs:
     * - Prevents duplicate events in the database
     * - Allows tracing of specific events in logs
     * - Ensures events can be uniquely identified even if created at the same millisecond
     *
     * @param orderId The redemption order identifier (required)
     * @param taskIds Optional prescription task identifier (can be null)
     * @return A unique event ID string
     */
    private fun generateId(orderId: String, taskIds: List<String> = emptyList()): String {
        // Get current time in UTC timezone to ensure consistency across different devices/timezones
        val now = Clock.System.now().toLocalDateTime(TimeZone.UTC)

        // Format timestamp as YYYYMMDDTHHmmss (e.g., 20231115T143022)
        // Using %04d and %02d ensures leading zeros (e.g., 01 instead of 1)
        val timestamp = "%04d%02d%02dT%02d%02d%02d".format(
            now.year,
            now.monthNumber,
            now.dayOfMonth,
            now.hour,
            now.minute,
            now.second
        )

        // Generate 16 random hexadecimal characters for uniqueness
        // This prevents ID collisions if two events are created in the same second
        val random = Random.nextBytes(8).joinToString("") {
            "%02x".format(it) // Convert each byte to a 2-digit hex string
        }

        // Build the final ID by concatenating all parts
        return buildString {
            append("evt_") // Event prefix
            append(orderId)

            // Only include taskId if it's not null or empty
            if (taskIds.isNotEmpty()) {
                append("_")
                append(taskIds.joinToString(separator = "_"))
            }

            append("_")
            append(timestamp)
            append("_")
            append(random)
        }
    }
}
